/** Job titles / positions for employees */
export const EMPLOYEE_POSITIONS = [
  // Leadership
  'CEO — Chief Executive Officer',
  'CTO — Chief Technology Officer',
  'CFO — Chief Financial Officer',
  'COO — Chief Operating Officer',
  'CMO — Chief Marketing Officer',
  'CHRO — Chief Human Resources Officer',
  'Founder',
  'Co-Founder',
  'Managing Director',
  'Director',
  'VP Engineering',
  'VP Sales',
  'VP Marketing',
  'VP Operations',
  'VP Product',

  // Management
  'Project Manager',
  'Product Manager',
  'Engineering Manager',
  'Team Lead',
  'Scrum Master',
  'Operations Manager',
  'Account Manager',
  'Business Development Manager',
  'Office Manager',

  // HR & Admin
  'HR Manager — Human Resources Manager',
  'HR Executive',
  'Recruiter',
  'Talent Acquisition Specialist',
  'Admin Executive',

  // Software / Engineering
  'Software Engineer',
  'Senior Software Engineer',
  'Junior Software Engineer',
  'Full Stack Developer',
  'MERN Stack Developer',
  'MEAN Stack Developer',
  'Frontend Developer',
  'Backend Developer',
  'Mobile App Developer',
  'React Developer',
  'React Native Developer',
  'Next.js Developer',
  'Node.js Developer',
  'Python Developer',
  'Django Developer',
  'Java Developer',
  'PHP Developer',
  'Laravel Developer',
  'DevOps Engineer',
  'Cloud Engineer',
  'QA Engineer — Quality Assurance',
  'Automation Test Engineer',
  'UI/UX Designer',
  'Graphic Designer',
  'Web Designer',

  // AI / Data
  'AI Engineer',
  'Machine Learning Engineer',
  'Data Scientist',
  'Data Analyst',
  'Data Engineer',
  'Business Analyst',
  'BI Analyst — Business Intelligence',
  'Prompt Engineer',

  // Marketing & Sales
  'Marketing Manager',
  'Digital Marketing Manager',
  'SEO Specialist',
  'SEM Specialist',
  'Content Writer',
  'Social Media Manager',
  'Performance Marketing Specialist',
  'Meta Ads Specialist',
  'Google Ads Specialist',
  'Brand Manager',
  'Sales Manager',
  'Sales Executive',
  'Inside Sales Representative',
  'Client Success Manager',

  // Support & Others
  'Customer Support Executive',
  'Technical Support Engineer',
  'Finance Executive',
  'Accountant',
  'Legal Advisor',
  'Consultant',
  'Intern',
  'Other',
] as const

export type EmployeePosition = (typeof EMPLOYEE_POSITIONS)[number]
